title: Scaleworks
email: thom@scaleworks.io
description: >
  Scaleworks is a Site Reliability Engineering consultancy. We have deep
  expertise in designing, engineering, and operating highly available,
  agile infrastructures that deliver value.
baseurl: ""
url: "http://scaleworks.io"
twitter_username: scaleworks_io
github_username:  thommay

markdown: kramdown
highlighter: rouge
timezone: Europe/London
future: true

links:
  - title: Writings
    url: /writings
  - title: Speaking
    url: /speaking
  - title: Contact Us
    url: /contact

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

sass:
    style: :compressed

permalink:   /:categories/:year/:month/:day/:title.html
